# Generated by Django 5.1.6 on 2026-04-17 17:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Tipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=512)),
                ('desc', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=512)),
                ('titulo_original', models.CharField(max_length=512)),
                ('idioma_original', models.CharField(max_length=80)),
                ('fecha_publicacion', models.DateField(blank=True, null=True)),
                ('anho_publicacion', models.IntegerField()),
                ('synopsis', models.TextField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diralibrary.tipo')),
            ],
        ),
        migrations.CreateModel(
            name='MetaData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipomd', models.CharField(max_length=200)),
                ('tag', models.CharField(max_length=200)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diralibrary.titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Credito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credito', models.CharField(max_length=200)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diralibrary.persona')),
                ('libro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diralibrary.titulo')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_ini', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('formato', models.CharField(max_length=128)),
                ('idioma', models.CharField(max_length=128)),
                ('unidades', models.CharField(max_length=128)),
                ('cantidad', models.IntegerField()),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diralibrary.titulo')),
            ],
        ),
    ]
