# Generated by Django 5.1.6 on 2026-04-18 00:09

import diralibrary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diralibrary', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cubiertas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=diralibrary.models.path_and_name)),
                ('caption', models.TextField()),
                ('tipo', models.CharField(max_length=30)),
                ('vista', models.BooleanField(default=False)),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diralibrary.titulo')),
            ],
        ),
    ]
