# Generated by Django 5.1.6 on 2026-04-19 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diralibrary', '0002_cubiertas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo', models.DateTimeField(auto_now_add=True)),
                ('texto', models.TextField()),
                ('titulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='diralibrary.titulo')),
            ],
        ),
    ]
