# Generated by Django 5.1.6 on 2026-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diralibrary', '0003_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumo',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
