# Generated by Django 5.1.6 on 2026-04-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diralibrary', '0004_alter_consumo_fecha_fin'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='encabezado',
            field=models.CharField(blank=True, default=None, max_length=512, null=True),
        ),
    ]
