# Generated by Django 5.1.6 on 2026-04-19 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diralibrary', '0005_comentario_encabezado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='es_personaje',
            field=models.BooleanField(default=False),
        ),
    ]
