# Generated by Django 5.1.6 on 2026-04-22 00:24

import diralibrary.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diralibrary', '0006_comentario_es_personaje'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encabezado', models.CharField(max_length=512)),
                ('fecha', models.DateField()),
                ('edicionTS', models.DateTimeField(auto_now=True)),
                ('tipo', models.CharField(max_length=512)),
                ('texto', models.TextField()),
                ('aplicaConsumo', models.BooleanField()),
                ('atributos', models.TextField()),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=diralibrary.models.path_and_name)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='diralibrary.entrada')),
            ],
        ),
    ]
