# Generated by Django 5.1.6 on 2025-09-30 20:40

import django.db.models.deletion
import thetimes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_edicion', models.DateTimeField()),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.category')),
            ],
        ),
        migrations.CreateModel(
            name='Consumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ini', models.DateField()),
                ('fec_fin', models.DateField(blank=True, null=True)),
                ('unidades', models.CharField(max_length=100)),
                ('cantidad', models.IntegerField()),
                ('multiplicador', models.IntegerField()),
                ('consumo', models.IntegerField()),
                ('formato', models.CharField(max_length=200)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.item')),
            ],
        ),
        migrations.CreateModel(
            name='AttrText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_name', models.CharField(max_length=255)),
                ('att_value', models.TextField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.item')),
            ],
        ),
        migrations.CreateModel(
            name='AttrItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rel_name', models.CharField(max_length=255)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='child_item', to='thetimes.item')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_item', to='thetimes.item')),
            ],
        ),
        migrations.CreateModel(
            name='AttrInteger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_name', models.CharField(max_length=255)),
                ('att_value', models.IntegerField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.item')),
            ],
        ),
        migrations.CreateModel(
            name='AttrImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(blank=True, max_length=255, null=True, upload_to=thetimes.models.path_and_name)),
                ('caption', models.TextField()),
                ('tipo', models.CharField(max_length=30)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.item')),
            ],
        ),
        migrations.CreateModel(
            name='AttrDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('att_name', models.CharField(max_length=255)),
                ('att_value', models.DateField()),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.item')),
            ],
        ),
    ]
