# Generated by Django 5.1.6 on 2025-10-01 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='consumido',
            field=models.BooleanField(default=False),
        ),
    ]
