# Generated by Django 5.1.6 on 2025-10-27 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0002_item_consumido'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('nombre_corto', models.CharField(max_length=15)),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('info', models.TextField()),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Torneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=256)),
                ('region', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Contrato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fec_ini', models.DateField(blank=True, null=True)),
                ('fec_fin', models.DateField(blank=True, null=True)),
                ('posicion', models.CharField(max_length=200)),
                ('dorsal', models.IntegerField()),
                ('last_edited', models.DateField(blank=True, null=True)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.equipo')),
                ('jugador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.jugador')),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('goles_local', models.IntegerField()),
                ('goles_visita', models.IntegerField()),
                ('rondap_local', models.IntegerField()),
                ('rondap_visita', models.IntegerField()),
                ('terminado', models.BooleanField()),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='local', to='thetimes.equipo')),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visita', to='thetimes.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.torneo')),
            ],
        ),
        migrations.CreateModel(
            name='Gol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('adicional', models.IntegerField()),
                ('penalty', models.BooleanField()),
                ('autogol', models.BooleanField()),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.contrato')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Alineacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=75)),
                ('contrato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.contrato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.equipo')),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.partido')),
            ],
        ),
        migrations.CreateModel(
            name='RelTorneoEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.equipo')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.torneo')),
            ],
        ),
    ]
