# Generated by Django 5.1.6 on 2025-10-27 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0003_equipo_jugador_torneo_contrato_partido_gol_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='partido',
            name='fase',
            field=models.CharField(default='MD', max_length=200),
        ),
    ]
