# Generated by Django 5.1.6 on 2025-10-27 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0004_partido_fase'),
    ]

    operations = [
        migrations.AddField(
            model_name='gol',
            name='gol_local',
            field=models.BooleanField(default=False),
        ),
    ]
