# Generated by Django 5.1.6 on 2025-10-28 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0005_gol_gol_local'),
    ]

    operations = [
        migrations.AddField(
            model_name='contrato',
            name='n_posicion',
            field=models.IntegerField(default=0),
        ),
    ]
