# Generated by Django 5.1.6 on 2025-11-13 17:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0007_journalentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttime', models.DateTimeField(auto_now_add=True)),
                ('ttext', models.CharField(max_length=2000)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.item')),
            ],
        ),
    ]
