# Generated by Django 5.1.6 on 2025-11-19 00:41

import thetimes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0008_tweet'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrimage',
            name='thumbnail',
            field=models.ImageField(editable=False, null=True, upload_to=thetimes.models.path_and_name),
        ),
    ]
