# Generated by Django 5.1.6 on 2025-11-19 01:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0009_attrimage_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attrimage',
            name='thumbnail',
        ),
    ]
