# Generated by Django 5.1.6 on 2025-12-18 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0010_remove_attrimage_thumbnail'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarraProgreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('progreso', models.IntegerField()),
                ('anterior', models.IntegerField()),
                ('consumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.consumo')),
            ],
        ),
    ]
