# Generated by Django 5.1.6 on 2026-01-20 19:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0011_barraprogreso'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atributos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('tipo', models.CharField(max_length=3)),
                ('nombre', models.CharField(max_length=500)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('entero', models.IntegerField(blank=True, null=True)),
                ('texto', models.TextField(blank=True, null=True)),
                ('decimal', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atributos', to='thetimes.item')),
            ],
        ),
    ]
