# Generated by Django 5.1.6 on 2026-02-04 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0012_atributos'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumo',
            name='inprogress',
            field=models.BooleanField(default=False),
        ),
    ]
