# Generated by Django 5.1.6 on 2026-02-04 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0013_consumo_inprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrinteger',
            name='vista',
            field=models.BooleanField(default=False),
        ),
    ]
