# Generated by Django 5.1.6 on 2026-02-04 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0014_attrinteger_vista'),
    ]

    operations = [
        migrations.AddField(
            model_name='attrimage',
            name='vista',
            field=models.BooleanField(default=False),
        ),
    ]
