# Generated by Django 5.1.6 on 2026-02-12 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0015_attrimage_vista'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotaPartido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minuto', models.IntegerField()),
                ('comentario', models.TextField()),
                ('partido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='thetimes.partido')),
            ],
        ),
    ]
