# Generated by Django 5.1.6 on 2026-03-15 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thetimes', '0017_album_beer_albumlog_beerlog_song'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='last_played',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
